install.packages("tidyverse")
install.packages("lubridate")
install.packages("janitor")
install.packages("dplyr")
library(tidyverse)
library(lubridate)
library(janitor)
library(dplyr)
Jul_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202207/202207-divvy-tripdata.csv")
Aug_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202208/202208-divvy-tripdata.csv")
Sep_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202209/202209-divvy-publictripdata.csv")
Oct_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202210/202210-divvy-tripdata.csv")
Nov_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202211/202211-divvy-tripdata.csv")
Dec_2022 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202212/202212-divvy-tripdata.csv")
Jan_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202301/202301-divvy-tripdata.csv")
Feb_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202302/202302-divvy-tripdata.csv")
Mar_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202303/202303-divvy-tripdata.csv")
Apr_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202304/202304-divvy-tripdata.csv")
May_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202305/202305-divvy-tripdata.csv")
Jun_2023 <- read.csv("C:/Users/Phizz/OneDrive/Desktop/Cyclistic Case Study/202306/202306-divvy-tripdata.csv")
trips_2022 <- rbind(Jul_2022, Aug_2022, Sep_2022, Oct_2022, Nov_2022, Dec_2022)
trips_2023 <- rbind(Jan_2023, Feb_2023, Mar_2023, Apr_2023, May_2023, Jun_2023)
all_trips <- rbind(trips_2022, trips_2023)
all_trips <- janitor::remove_empty(dat = all_trips,which = c("cols"))
all_trips <- janitor::remove_empty(dat = all_trips,which = c("rows"))
dim(all_trips)
all_trips <- all_trips %>%  
  select(-c(start_lat, start_lng, end_lat, end_lng, start_station_name, start_station_id, end_station_name, end_station_id))
all_trips$started_at <- lubridate::as_datetime(all_trips$started_at)
all_trips$ended_at <- lubridate::as_datetime(all_trips$ended_at)
all_trips <- all_trips %>%
  mutate(
    date = as.Date(started_at),
    month = month(started_at),
    day = day(started_at),
    year = year(started_at),
    day_of_week = wday(started_at, label = TRUE),
    start_time = paste(hour(started_at), minute(started_at), sep = ":"),
    end_time = paste(hour(ended_at), minute(ended_at), sep = ":"))
all_trips$length_min <- difftime(all_trips$ended_at, all_trips$started_at, units = "mins")
all_trips$length_min <- round(as.numeric(all_trips$length_min), 3)
all_trips$length_hr <- difftime(all_trips$ended_at, all_trips$started_at, units = "hours")
all_trips$length_hr <- round(as.numeric(all_trips$length_hr), 2)
all_trips$started_at <- as.POSIXct(all_trips$started_at, format = date_format)
all_trips$ended_at <- as.POSIXct(all_trips$ended_at, format = date_format)
all_trips$ride_length <- difftime(all_trips$ended_at, all_trips$date)
mean_ride_length <- mean(all_trips$ride_length)
median_ride_length <- median(all_trips$ride_length)
max_ride_length <- max(all_trips$ride_length)
min_ride_length <- min(all_trips$ride_length)
aggregate(all_trips$ride_length ~ all_trips$member_casual, FUN = mean)
aggregate(all_trips$ride_length ~ all_trips$member_casual, FUN = median)
aggregate(all_trips$ride_length ~ all_trips$member_casual, FUN = max)
aggregate(all_trips$ride_length ~ all_trips$member_casual, FUN = min)
write.csv(all_trips, file = "cyclist_data_tableau.csv", row.names = FALSE)